window.FEISHU_PROJECTS = [
  {
    "id": "rec25v3tGmrDdx",
    "source": "feishu",
    "name": "西昊",
    "status": "停滞",
    "startDate": "2025-11-17",
    "cycleDays": 377,
    "progressPercent": 47,
    "kpi": "人体工学椅、办公椅、电竞椅、电脑椅排名前三",
    "platform": "全平台5及以上",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈、张扬",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/GckTwsRTni879KkUFfQctuMCnoh"
      }
    ],
    "kpiStatus": "停滞待处理",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": [
      {
        "label": "氧气科技 西昊GEO SOLUTION1021final.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "F246bPExNomnc3xOJOxcmTkCnDf",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 45365379
      },
      {
        "label": "第二个月【简洁版】 西昊x氧气 GEO月报.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "FckebtwUuoI9kRxcI4gcm1VinPf",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 24023616
      },
      {
        "label": "第三个月 西昊x氧气 GEO月报 1.22-2.22.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "XVPUbINv8obyk8xDka0cdxU2nJr",
        "fileType": "application/pdf",
        "size": 3593312
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recveNaDKVJG3t",
    "source": "feishu",
    "name": "西昊2",
    "status": "停滞",
    "startDate": "2026-01-11",
    "cycleDays": 365,
    "progressPercent": 35,
    "kpi": "撑腰护背久坐不累，实现在该关键词下的品牌排名第一（跨品类总排名第一）考核标准：首月仅考核最后一周，即3个平台完成天数≥4，则视为完成(如上表，第一月第4周完成天数为3，为视为未完成);第二个月开始进入正常考核周期：每个平台、每周周一至周五(含节假日)，即每月20天，任意完成天数≥16，则视为本月100%达标。",
    "platform": "DeepSeek、豆包、文心一言",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "停滞待处理",
    "currentData": "当前完成度 35%",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNlgg5OPg6",
    "source": "feishu",
    "name": "可口可乐",
    "status": "已完成",
    "startDate": "2025-12-02",
    "cycleDays": 31,
    "progressPercent": 100,
    "kpi": "负面关联降低",
    "platform": "微博智搜",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/QkMywkQRIi1ko3ku0sfcvQr0nGb"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "1.28可口可乐x氧气结案报告.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "ItUvbWUFxoSjSWxHyHUc99mznzg",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 14633171
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recveNouG3UhTD",
    "source": "feishu",
    "name": "茶马古窖",
    "status": "已完成",
    "startDate": "2025-02-11",
    "cycleDays": 337,
    "progressPercent": 100,
    "kpi": "个人ip",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈、刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/ZYRywZbsVisSyCk7e8YcBUO5nzd"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "【结案月报】 茶马古窖x氧气 GEO月报.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "WPz5bRzY0oO6VLxmk7mcP2MinSh",
        "fileType": "application/pdf",
        "size": 1620759
      }
    ],
    "briefLinks": [
      {
        "label": "240802定稿-茶马古窖项目介绍折页.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "Vy6Ob1m0AoTElCxdkiWc8RUYnqb",
        "fileType": "application/pdf",
        "size": 1505391
      }
    ]
  },
  {
    "id": "recvm25hMZaywX",
    "source": "feishu",
    "name": "湄洲岛",
    "status": "已完成",
    "startDate": "2025-12-16",
    "cycleDays": 5,
    "progressPercent": 100,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "张扬",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/FPtlwteXAiIJNSkG22qcmU9enPw"
      }
    ],
    "kpiStatus": "已完成待补 KPI",
    "currentData": "已关联 1 个监测表入口；项目周期已结束，待补充 KPI 与结案资料。",
    "optimizationSuggestion": "补充项目 KPI 与平台信息；监测表已关联，后续可归档结案报告。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNpiTYQzHi",
    "source": "feishu",
    "name": "太太乐松茸鲜",
    "status": "进行中",
    "startDate": "2026-02-09",
    "cycleDays": 365,
    "progressPercent": 33,
    "kpi": "10个关键词排名第一\n需要发稿500篇（-27.4.14）",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "梁伟安",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/MZBYwDkEJirM5kkXbSicUTPQn8f?sheet=BWsvDf"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/OPYxwvF9CiWCV9ksQfHcv0cunZb?sheet=vcWSnP"
      }
    ],
    "kpiStatus": "部分未达标",
    "currentData": "发稿表已读取 4 个工作表，有效发布链接 304 条；发稿 KPI 304/500 篇，还差 196 篇。\n监测口径已修正：6.9 子表为空，未纳入；本次统计 6.1 与 6.8 两个子表。\n6.8：松茸鲜 Top1 5/6=83.3%，Top3 6/6=100%；松茸调料 Top1 4/6=66.7%，Top3 6/6=100%。\n6.8：煲汤提鲜调味料品牌 Top1 5/6=83.3%，Top3 6/6=100%；替代味精的调料品品牌 Top1 4/6=66.7%，Top3 6/6=100%。\n6.8：馅料调味料品牌 Top1 5/6=83.3%，Top3 6/6=100%；凉拌菜提鲜调料品品牌 Top1 6/6=100%，Top3 6/6=100%。\n6.8：追求健康生活家庭选择的调味料品牌 Top1 3/6=50%，Top3 4/6=66.7%；提鲜调味料品牌 Top1 4/6=66.7%，Top3 6/6=100%。\n6.8：0添加提鲜调料品牌 Top1 2/6=33.3%，Top3 6/6=100%；家常菜常备调料品牌 Top1 3/6=50%，Top3 3/6=50%。\n6.1：松茸鲜 Top1 34/42=81%，Top3 42/42=100%；松茸调料 Top1 30/42=71.4%，Top3 42/42=100%。\n6.1：煲汤提鲜调味料品牌 Top1 39/42=92.9%，Top3 40/42=95.2%；替代味精的调料品品牌 Top1 14/42=33.3%，Top3 34/42=81%。\n6.1：馅料调味料品牌 Top1 27/42=64.3%，Top3 36/42=85.7%；凉拌菜提鲜调料品品牌 Top1 28/42=66.7%，Top3 32/42=76.2%。\n6.1：追求健康生活家庭选择的调味料品牌 Top1 10/42=23.8%，Top3 32/42=76.2%；提鲜调味料品牌 Top1 34/42=81%，Top3 36/42=85.7%。\n6.1：0添加提鲜调料品牌 Top1 12/42=28.6%，Top3 42/42=100%；家常菜常备调料品牌 Top1 18/42=42.9%，Top3 19/42=45.2%。",
    "optimizationSuggestion": "6.8 当前主要缺口：家常菜常备调料品牌 Top3 为 3/6，距离 4/6 还差 1 个平台；0添加提鲜调料品牌 Top1 仅 2/6、追求健康生活家庭选择的调味料品牌 Top1 3/6，建议加强对应关键词的发稿与信源覆盖。发稿数量目前 304/500，还差 196 篇，需继续补量并同步维护 6.9 后续监测。",
    "reportLinks": [
      {
        "label": "太太乐0504-0531监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "QNZubWcUDo5vDHxJgo4cXbQTntd",
        "fileType": "application/pdf",
        "size": 603268
      },
      {
        "label": "太太乐0511-0517监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "H9qSb57f7oR0ILxi8O5cZfDqnDd",
        "fileType": "application/pdf",
        "size": 687611
      },
      {
        "label": "太太乐0518-0524监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "Y36hbTlmXoau8vxSfyNcoVTknlf",
        "fileType": "application/pdf",
        "size": 865416
      },
      {
        "label": "太太乐松茸鲜_GEO_审计报告_(0511-0517).docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "MHj1bx8wjovQbuxCdgicdebRntf",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 23170
      },
      {
        "label": "太太乐0525-0531监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "MkBSbo3HvoCjPsxQyIrc1JxlncS",
        "fileType": "application/pdf",
        "size": 665018
      },
      {
        "label": "太太乐GEO监测报告（0518-0524）.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "T16cbE1C4owpPYx9YzqcidkXnXg",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 164563
      },
      {
        "label": "太太乐GEO监测报告（0525-0531）.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "AqXHbgDCzoCwfyxJg2wcoWkun4f",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 179670
      },
      {
        "label": "太太乐0601-0607监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "IDigbnu0Go6VaOxxzXyckigxnug",
        "fileType": "application/pdf",
        "size": 499019
      },
      {
        "label": "太太乐松茸鲜GEO监测报告部分（5月10日）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "SvBJbnte9ogZt8xUBFqcqY70nug",
        "fileType": "application/pdf",
        "size": 1020810
      },
      {
        "label": "太太乐GEO监测报告（0601-0607）.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "JSHDb1Tm8oEdxCxY1dncXUM1nDg",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 179983
      }
    ],
    "briefLinks": [
      {
        "label": "太太乐原味鲜松茸鲜产品介绍.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "EU0wbEc9CoF42gxVXjicRfRgnGb",
        "fileType": "application/pdf",
        "size": 1566570
      },
      {
        "label": "太太乐松茸鲜GEO项目-核心关键词&长尾词（5.15更新）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "M3yQbRgCfoYPjIx6CHZcb6LOnzg",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 12587
      }
    ]
  },
  {
    "id": "recveNplOcrpKw",
    "source": "feishu",
    "name": "李锦记",
    "status": "已完成",
    "startDate": "2026-02-11",
    "cycleDays": 28,
    "progressPercent": 100,
    "kpi": "4个关键词排名前三",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "宋芷桐、刘依晨",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/YLZcwYwFxivdUckaovgc4V4ynyh"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/CIjVwvhj2idT9wkKpmNcSL98nmh"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个发稿资料入口；已关联 1 个监测表入口",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "李锦记月度监测与洞察报告0317.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "KxyLbR3HpoaEL2xkw4EcFSKtn7b",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 20092411
      },
      {
        "label": "李锦记薄盐生抽GEO第二阶段监测报告（３月12日结案）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "BVRCbeIN1oEkz2xFvXWcdLC4ngd",
        "fileType": "application/pdf",
        "size": 2202942
      },
      {
        "label": "深演×李锦记月度合作复盘与后续优化建议.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "IHJkbrTQdoTnZvxqLcrc4kL4nsd",
        "fileType": "application/pdf",
        "size": 2900913
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recveNplOcTlEG",
    "source": "feishu",
    "name": "一丰",
    "status": "已完成",
    "startDate": "2026-02-05",
    "cycleDays": 59,
    "progressPercent": 100,
    "kpi": "1个关键词被收录",
    "platform": "DeepSeek",
    "notes": "",
    "manager": "飞书用户6916HP",
    "writer": "辛味珈、刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "2.6-3.6一汽丰田月报.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "GqGbbpFMWoRpcTxXMPncyJYDnRb",
        "fileType": "application/pdf",
        "size": 1708118
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recveNplOciJ1c",
    "source": "feishu",
    "name": "驾校一点通",
    "status": "已完成",
    "startDate": "2026-02-23",
    "cycleDays": 28,
    "progressPercent": 100,
    "kpi": "4个关键词排名前三",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "赵博宇",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/sheets/LEqSs3Vsmhn8vEt8BAscioL1nob"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/EgLLwBbWXiQokskbPYacSSOSnxf"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个发稿资料入口；已关联 1 个监测表入口",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "【驾校一点通】GEO月度监测与洞察报告0330.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "WRRgbijTHo50uixIyDJcyl5tnQh",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 51778577
      },
      {
        "label": "驾校一点通GEO监测报告V1.0（3月24日）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "XWdvbHLseolLSMxHFtWcI6IRnDc",
        "fileType": "application/pdf",
        "size": 2123629
      },
      {
        "label": "驾校一点通GEO监测报告V1.0（3月10日）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "QQVgbUEinoc3ouxMrCQcSGK2nmx",
        "fileType": "application/pdf",
        "size": 1760069
      }
    ],
    "briefLinks": [
      {
        "label": "58驾培集团画册0402(1).pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "AdF3bkIfDotnQBxIzN1cWvKhnHf",
        "fileType": "application/pdf",
        "size": 41668304
      }
    ]
  },
  {
    "id": "recveNplOcdyyk",
    "source": "feishu",
    "name": "华硕",
    "status": "进行中",
    "startDate": "2026-04-12",
    "cycleDays": 90,
    "progressPercent": 67,
    "kpi": "1.在服务周期结束时，该语义包在指定的主流AI大模型矩阵（按照本次项目指定的五大平台：DeepSeek、豆包、kimi、腾讯元宝、通义千问）中的智能搜索结果，实现正面、准确信息的覆盖率为5个的大模型平台华硕主板，华硕商城在推荐位≥3位。2.从项目启动开始的20天需要看到优化结果，从项目启动30天需要看到稳定的优化结果，一直到项目合作结束。需提供必要的搜索验证页面截图（至少30个账号）3.一个季度发稿不少于150篇，需要提供所有发稿链接4.报告反馈：双周报、月报（PPT）、结案报告（PPT）",
    "platform": "5个平台",
    "notes": "",
    "manager": "马朔",
    "writer": "马朔",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/KbsdwkRTBizuvgkePKOcvyGAnlb?sheet=QhQovf"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/VzrDwYafWixoRqkTMdHcBKupngx?sheet=DGmpZZ"
      }
    ],
    "kpiStatus": "未达标",
    "currentData": "发稿表已按子项目核对：华硕主板 100/150 篇，还差 50 篇；华硕商城 78/150 篇，还差 72 篇。\n两个子项目均要求各 150 篇，不能按主板+商城合并总数判断达标。\n监测表已读取 4 个工作表：4.10、4.20、5.8、6.3；共识别 1197 条有效排名数据。\n排名表现：Top1 1059/1197，占 88.5%；Top3 1192/1197，占 99.6%；Top10 1197/1197，占 100%。\n监测结论：排名基本稳定在第一，当前主要未达标项不是排名，而是主板/商城两个子项目各自的发稿数量。",
    "optimizationSuggestion": "优先补齐发稿缺口：华硕主板补 50 篇、华硕商城补 72 篇；排名侧目前 Top1 占 88.5%，继续保持监测表按周更新，重点防止“未推荐品牌/推荐其他产品”的少数样本回落。",
    "reportLinks": [
      {
        "label": "华硕主板GEO优化双周报0603.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "E9srb3Wr3oO1U7xLAW4c2FfDntg",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 16905212
      },
      {
        "label": "华硕主板GEO优化双周报0429.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "MT6fbNRI2oIO2sxCYogceYlFn1e",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 15233597
      },
      {
        "label": "华硕主板GEO优化月报0516.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "MvVnb92jYo3AFaxvJ4KcyH89n6j",
        "fileType": "application/pdf",
        "size": 9172397
      },
      {
        "label": "华硕商城GEO优化月报汇报0516.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "SE91bDkk3o6UfdxArBhcGVlhnYd",
        "fileType": "application/pdf",
        "size": 7587848
      },
      {
        "label": "华硕主板GEO优化双周报（第2月双周报）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "GQowbgkeqoBEunx4UlScjqignoE",
        "fileType": "application/pdf",
        "size": 5444463
      }
    ],
    "briefLinks": [
      {
        "label": "核心竞品产品优劣势对比分析、定位与核心卖点差异.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "A07rbHAEQobscqxqMf9cftjfnag",
        "fileType": "application/pdf",
        "size": 505279
      },
      {
        "label": "AMD 平台.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "ZAgPbNyOToj6uexVJvicCVYpnzf",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 15735
      },
      {
        "label": "华硕商城全面解析：介绍、优势与竞品对比.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "SFddbKIRQo6tCjxe6IKcvc4lnhf",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 116167
      },
      {
        "label": "Intel 平台.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "Jx7cbOKuNovxAcxttzwcpXXUnPh",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 17980
      }
    ]
  },
  {
    "id": "recveNplOcfxZ1",
    "source": "feishu",
    "name": "全标",
    "status": "已完成",
    "startDate": "2025-10-11",
    "cycleDays": 14,
    "progressPercent": 100,
    "kpi": "AI咨询",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOcfeUR",
    "source": "feishu",
    "name": "7 THLAT",
    "status": "已完成",
    "startDate": "2026-03-16",
    "cycleDays": 30,
    "progressPercent": 100,
    "kpi": "品牌名 信息正确展现",
    "platform": "豆包，千问",
    "notes": "",
    "manager": "刘依晨",
    "writer": "邢瑜轩",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "3.17-4.16 7THLAT结案报告(1).pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "IJ13b2JGioTEqfxCWihck4XJnfV",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 17807998
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recveNplOcxETh",
    "source": "feishu",
    "name": "公交",
    "status": "已完成",
    "startDate": "2026-03-23",
    "cycleDays": 30,
    "progressPercent": 100,
    "kpi": "三个关键词覆盖度>60%",
    "platform": "大于等于3个主流AI大模型",
    "notes": "",
    "manager": "金雨婷",
    "writer": "金雨婷",
    "publisher": "刘依晨",
    "monitor": "金雨婷、刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "宝苑公共交通传媒月报.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "PhJkbNF12ouvFfxkyrWckpMEnWe",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 30472420
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recveNplOcWAzC",
    "source": "feishu",
    "name": "祖玛珑",
    "status": "已完成",
    "startDate": "2026-03-29",
    "cycleDays": 51,
    "progressPercent": 100,
    "kpi": "核心：TOP3%，TOP3 RANKING，SOV%，SOV RANKING\n参考：信源引用率",
    "platform": "豆包app",
    "notes": "",
    "manager": "赵博宇",
    "writer": "邢瑜轩",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "【JML】GEO双周报W6-5.11-MZ监测.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "NftobtWexowU2oxmA23ccZufnTb",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 484530
      },
      {
        "label": "【JML】GEO双周报W4-4.27-MZ监测.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "NgHQbNJfNo2fr6xj3oRcSpaTnqb",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 143244
      }
    ],
    "briefLinks": [
      {
        "label": "Jo Malone发稿规划3.23.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "JfNebg6vQoWI1QxUSY3cI4dCnBt",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 1810789
      },
      {
        "label": "雅诗兰黛综合信息表0402-ZML新增关键词.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "UFjTb6ilgoM80kxTptBcIUmpnDe",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 36529
      }
    ]
  },
  {
    "id": "recveNplOcnwiZ",
    "source": "feishu",
    "name": "mac",
    "status": "停滞",
    "startDate": "2026-03-29",
    "cycleDays": 92,
    "progressPercent": 52,
    "kpi": "核心：TOP3%，TOP3 RANKING，SOV%，SOV RANKING\n参考：信源引用率",
    "platform": "豆包app+deepseek",
    "notes": "",
    "manager": "赵博宇",
    "writer": "马朔",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "停滞待处理",
    "currentData": "当前完成度 52%",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": [],
    "briefLinks": [
      {
        "label": "MAC GEO发稿规划3.19.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "BkltbU0joopGMVxahwRceI4gnBc",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 3392268
      },
      {
        "label": "雅诗兰黛综合信息表0402-ZML新增关键词.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "X3Akb9uYaoGCTkxL0mwcingence",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 36529
      }
    ]
  },
  {
    "id": "recveNplOcetxW",
    "source": "feishu",
    "name": "海蓝之谜",
    "status": "停滞",
    "startDate": "2026-03-29",
    "cycleDays": 92,
    "progressPercent": 54,
    "kpi": "核心：TOP3%，TOP3 RANKING，SOV%，SOV RANKING\n参考：信源引用率",
    "platform": "豆包app",
    "notes": "",
    "manager": "赵博宇",
    "writer": "赵博宇",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "停滞待处理",
    "currentData": "当前完成度 54%",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": [
      {
        "label": "309a7657d5037fb2a08312e21c699d8e.png",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "ZCgqbvAqRofuIoxamricfqzFnkh",
        "fileType": "image/png",
        "size": 83818
      }
    ],
    "briefLinks": [
      {
        "label": "雅诗兰黛综合信息表0402-ZML新增关键词.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "JRGhbhmpJo2BpCxWOUAcAJblnDc",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 36529
      }
    ]
  },
  {
    "id": "recveNplOcXYmU",
    "source": "feishu",
    "name": "欧莱雅",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOcjm2W",
    "source": "feishu",
    "name": "作业帮",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOc7fXw",
    "source": "feishu",
    "name": "施耐德",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOceANM",
    "source": "feishu",
    "name": "babycare招标",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "3月24日递交应标文件@向昱筱Cheryl Xiang ✅",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOc4DBR",
    "source": "feishu",
    "name": "招行信用卡",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOcE3VX",
    "source": "feishu",
    "name": "贵州天马",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOc37li",
    "source": "feishu",
    "name": "谷雨",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOcECQL",
    "source": "feishu",
    "name": "嘉立创",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOcIuxf",
    "source": "feishu",
    "name": "施耐德",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "本周完成竞标方案@向昱筱Cheryl Xiang",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOc0BKa",
    "source": "feishu",
    "name": "时空宇道",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "本周完成竞标方案@向昱筱Cheryl Xiang",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOcszqo",
    "source": "feishu",
    "name": "中商联数据委",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "@向昱筱Cheryl Xiang @马朔",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recveNplOctD7v",
    "source": "feishu",
    "name": "wonderlab",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "@向昱筱Cheryl Xiang本周五前给方案",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvgopfFqMfp4",
    "source": "feishu",
    "name": "理想",
    "status": "已完成",
    "startDate": "2026-04-09",
    "cycleDays": 5,
    "progressPercent": 100,
    "kpi": "- 关键指标与现状：产品展示度（产品展示度 = （提及次数 / 提问次数） × 100%），现状值约48%",
    "platform": "Deepseek",
    "notes": "",
    "manager": "辛味珈、飞书用户6916HP",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/LEc9wkYGHiuVT5kLmVUcN2I7nzg"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvhXpRFrA1MC",
    "source": "feishu",
    "name": "哲库林 润喉糖",
    "status": "进行中",
    "startDate": "2026-05-07",
    "cycleDays": 153,
    "progressPercent": 23,
    "kpi": "- 优化目标：产品展示度，提升至不低于90%",
    "platform": "DeepSeek、豆包、Kimi、通义千\n问、元宝中的80%有效收录",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/V0MZwOwgWicvockfGZicr0r1nvb"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 1 个工作表，有效发布链接 49 条。\n尚未关联监测表，暂无法判断近一周/近一月趋势。",
    "optimizationSuggestion": "继续更新本周监测数据；如发稿数量或排名未达预期，补充差距说明。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvhXpWChLgnp",
    "source": "feishu",
    "name": "爱菊学校",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "- 优化周期：启动优化执行后3-5天，指标达到目标值，并保持3天指标不低于90%",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvhXq5d4Oxv0",
    "source": "feishu",
    "name": "海尔（卡萨帝）",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvhXqn6kl16F",
    "source": "feishu",
    "name": "雀巢",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇、飞书用户6916HP",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvhXqxeQlGwN",
    "source": "feishu",
    "name": "珍致",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇、飞书用户6916HP",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvhXr75uIOhW",
    "source": "feishu",
    "name": "骨科医生",
    "status": "待开始",
    "startDate": "2026-04-19",
    "cycleDays": 37,
    "progressPercent": 0,
    "kpi": "信息正确展露，收录并推荐吴敏飞医生",
    "platform": "Deepseek 千问 豆包",
    "notes": "",
    "manager": "刘依晨",
    "writer": "刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [
      {
        "label": "吴敏飞教授AI语料优化结案报告(2).pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "CvWibY5cooaDPxxtnTVcLNybnRd",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 13684131
      }
    ],
    "briefLinks": []
  },
  {
    "id": "recvhXr8SD77ql",
    "source": "feishu",
    "name": "乳腺癌医生",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "邢瑜轩",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvjh9izeBYrC",
    "source": "feishu",
    "name": "igus",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvjheWColObr",
    "source": "feishu",
    "name": "一丰 荣放 亚洲龙",
    "status": "进行中",
    "startDate": "2026-05-05",
    "cycleDays": 91,
    "progressPercent": 41,
    "kpi": "亚洲龙KPI的考核：\n提升目标：声量SOV ：≥15%；TOP3推荐度：≥30%；TOP10推荐度：≥80%\n优化稿件：>= 100篇\n\n荣放KPI的考核\n提升目标：声量SOV ：≥15%；TOP3推荐度：≥20%；TOP10推荐度：≥80%",
    "platform": "5个平台",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/XDQhwi6bTiZVrlkmQQEch7Bgn0c",
        "label": "一丰荣放亚洲龙 发稿附表"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "部分未达标",
    "currentData": "正式发稿附表已读取：有效发布链接 90 条，其中荣放 36 条、亚洲龙 54 条。\n发稿 KPI：90/100 篇，还差 10 篇；以新飞书附表为准，之前本地周报统计口径已废弃。\n亚洲龙 6/7 KPI 表：6 个基础词的 SOV、Top3、Top10 综合值均达标；最新综合 SOV 20.6%-27.7%、Top3 57.0%-68.9%、Top10 82.7%-89.3%。\n荣放 5/20 点检表：Top3 38.51% 已超过 ≥20%；SOV 7.63% 距 ≥15% 还差 7.37 个百分点；Top10 47.24% 距 ≥80% 还差 32.76 个百分点。",
    "optimizationSuggestion": "先补齐正式发稿附表中的 10 篇发布缺口；荣放侧继续重点补 SOV 与 Top10，增加汽车垂媒/问答信源覆盖，围绕“15万左右通勤SUV、城市SUV、家用SUV”等词做定向发布和监测复盘。",
    "reportLinks": [
      {
        "label": "亚洲龙-5月14号-GEO截图.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "JDOnb6zPlo2tihxcfNncVjzwn5z",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 55134846
      },
      {
        "label": "荣放-5月14号-GEO截图.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "AiXWbDC8jopFdAxkj67cPYYwnUd",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 28867749
      },
      {
        "label": "【亚洲龙】基础词数据&信源-截至6.7.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "W9OCbyuLAoYvR0xEzDBcT5ksnGb",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 1188592
      },
      {
        "label": "一汽丰田-荣放GEO诊断项目-周报0501至0514（深演）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "H926bMbqxoe1bHxNgD7cy0HFnFg",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 583034
      },
      {
        "label": "周报点检-车型GEO优化进展（深演）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "OH1XbAf1KoGBS4xXFHlcqMRInCd",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 16103
      },
      {
        "label": "一汽丰田-亚洲龙GEO诊断项目-周报0511至0517（深演）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "WQ1MbrKQWo9niuxwY1AcxNhfn2c",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 586388
      },
      {
        "label": "一丰geo 5月阶段分析.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "NcdzbkqYTogt0xxS9yocvzHcnwh",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 151938
      }
    ],
    "briefLinks": [
      {
        "label": "一汽丰田荣放RAV4_GEO_Brief_氧气0429.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "IoUwbshfnojdyax3T9jcuUJNnth",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 28594
      },
      {
        "label": "一汽丰田亚洲龙GEO_Brief_0429.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "TECnbIUIBopnW9xgzhEcmMrRn0d",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 30876
      }
    ]
  },
  {
    "id": "recvjhfX2i6zgu",
    "source": "feishu",
    "name": "智美",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "宋芷桐",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvjW5TB0WiZd",
    "source": "feishu",
    "name": "格力高",
    "status": "进行中",
    "startDate": "2026-06-07",
    "cycleDays": 24,
    "progressPercent": 17,
    "kpi": "收录即可 \n有目标信源\n一个月投放20篇稿件",
    "platform": "五个平台",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "飞书已核对：项目已于 2026-06-07 开启，当前进度 4%。\nKPI：收录即可；有目标信源；一个月投放 20 篇稿件。\n当前尚未关联发稿链接和监测表，暂无法统计发布数量与收录情况。",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": [
      {
        "label": "格力高儿童益生菌_AI平台月度维护执行方案v2.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "WPSQbqsxvo4TgOxDO7jcB9p1nvb",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 466514
      }
    ]
  },
  {
    "id": "recvjW5VFLM2L1",
    "source": "feishu",
    "name": "深演",
    "status": "进行中",
    "startDate": "2026-05-14",
    "cycleDays": 30,
    "progressPercent": 93,
    "kpi": "大模型关键词正向提及率超过90%，需要发稿大于36篇（提供发稿链接）",
    "platform": "",
    "notes": "",
    "manager": "宋芷桐",
    "writer": "宋芷桐",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/Fe3uwVLCViswdxkzRKUcaQzqnug"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 1 个工作表，有效发布链接 53 条。\n发稿 KPI：53/36 篇，已达到数量要求。\n尚未关联监测表，暂无法判断近一周/近一月趋势。",
    "optimizationSuggestion": "继续更新本周监测数据；如发稿数量或排名未达预期，补充差距说明。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvjW6XlvkgV3",
    "source": "feishu",
    "name": "半亩花田",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvkB4pIdAQ48",
    "source": "feishu",
    "name": "长安汽车",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvkB4roXUK2R",
    "source": "feishu",
    "name": "咪咕",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvkB4MgLZqyP",
    "source": "feishu",
    "name": "万豪",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvkB4Qxo6Obm",
    "source": "feishu",
    "name": "自然堂",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvkB54wk2Wq0",
    "source": "feishu",
    "name": "pxn",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvld4x7F5xhp",
    "source": "feishu",
    "name": "赏·会所",
    "status": "进行中",
    "startDate": "2026-05-31",
    "cycleDays": 91,
    "progressPercent": 12,
    "kpi": "优化 14 天起出效果，第一个月收录，第二个月进前 5，第三个月到前 3\n发稿要求：第一个月目标是收录，每篇发 2-3 个媒体，暂未要求稿件数据",
    "platform": "六个平台中四个及以上，80%时间",
    "notes": "",
    "manager": "宋芷桐",
    "writer": "宋芷桐",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/RmRwwx6XKiyvxZkI1zBcE5OZnzf"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 1 个工作表，有效发布链接 7 条。\n尚未关联监测表，暂无法判断近一周/近一月趋势。",
    "optimizationSuggestion": "继续更新本周监测数据；如发稿数量或排名未达预期，补充差距说明。",
    "reportLinks": [],
    "briefLinks": []
  },
  {
    "id": "recvln50lusVeg",
    "source": "feishu",
    "name": "北京大学深圳研究生院",
    "status": "待开始",
    "startDate": "",
    "cycleDays": 0,
    "progressPercent": 0,
    "kpi": "收录即可\n五个关键词",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [],
    "briefLinks": []
  }
];
window.FEISHU_SYNC_META = {
  "syncedAt": "2026-06-09T16:57:03.156Z",
  "source": "feishu",
  "recordCount": 49,
  "note": "main-table-sync-v20",
  "preservedAnalysis": [
    "太太乐松茸鲜",
    "华硕",
    "一丰 荣放 亚洲龙"
  ],
  "progressUpdatedAt": "2026-06-09T16:58:18.296Z",
  "progressUpdateNote": "progress-only"
};
