window.FEISHU_PROJECTS = [
  {
    "id": "rec25v3tGmrDdx",
    "source": "feishu",
    "name": "西昊",
    "status": "停滞",
    "startDate": "2025-11-17",
    "cycleDays": 377,
    "progressPercent": 47,
    "kpi": "人体工学椅、办公椅、电竞椅、电脑椅排名前三",
    "platform": "全平台5及以上",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈、张扬",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNaDKVJG3t",
    "source": "feishu",
    "name": "西昊2",
    "status": "停滞",
    "startDate": "2026-01-11",
    "cycleDays": 365,
    "progressPercent": 35,
    "kpi": "撑腰护背久坐不累，实现在该关键词下的品牌排名第一（跨品类总排名第一）考核标准：首月仅考核最后一周，即3个平台完成天数≥4，则视为完成(如上表，第一月第4周完成天数为3，为视为未完成);第二个月开始进入正常考核周期：每个平台、每周周一至周五(含节假日)，即每月20天，任意完成天数≥16，则视为本月100%达标。",
    "platform": "DeepSeek、豆包、文心一言",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNlgg5OPg6",
    "source": "feishu",
    "name": "可口可乐",
    "status": "已完成",
    "startDate": "2025-12-02",
    "cycleDays": 31,
    "progressPercent": 100,
    "kpi": "负面关联降低",
    "platform": "微博智搜",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNouG3UhTD",
    "source": "feishu",
    "name": "茶马古窖",
    "status": "已完成",
    "startDate": "2025-02-11",
    "cycleDays": 337,
    "progressPercent": 100,
    "kpi": "个人ip",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈、刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNpiTYQzHi",
    "source": "feishu",
    "name": "太太乐松茸鲜",
    "status": "进行中",
    "startDate": "2026-02-09",
    "cycleDays": 365,
    "progressPercent": 32,
    "kpi": "10个关键词排名第一，500篇（-27.4.14）",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "梁伟安",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcrpKw",
    "source": "feishu",
    "name": "李锦记",
    "status": "已完成",
    "startDate": "2026-02-11",
    "cycleDays": 28,
    "progressPercent": 100,
    "kpi": "4个关键词排名前三",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "宋芷桐、刘依晨",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcTlEG",
    "source": "feishu",
    "name": "一丰",
    "status": "已完成",
    "startDate": "2026-02-05",
    "cycleDays": 59,
    "progressPercent": 100,
    "kpi": "1个关键词被收录",
    "platform": "DeepSeek",
    "notes": "",
    "manager": "飞书用户6916HP",
    "writer": "辛味珈、刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOciJ1c",
    "source": "feishu",
    "name": "驾校一点通",
    "status": "已完成",
    "startDate": "2026-02-23",
    "cycleDays": 28,
    "progressPercent": 100,
    "kpi": "4个关键词排名前三",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "赵博宇",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcdyyk",
    "source": "feishu",
    "name": "华硕",
    "status": "进行中",
    "startDate": "2026-04-12",
    "cycleDays": 91,
    "progressPercent": 88,
    "kpi": "1.在服务周期结束时，该语义包在指定的主流AI大模型矩阵（按照本次项目指定的五大平台：DeepSeek、豆包、kimi、腾讯元宝、通义千问）中的智能搜索结果，实现正面、准确信息的覆盖率为5个的大模型平台华硕主板，华硕商城在推荐位≥3位。\n2.从项目启动开始的20天需要看到优化结果，从项目启动30天需要看到稳定的优化结果，一直到项目合作结束。需提供必要的搜索验证页面截图（至少30个账号）\n3.一个季度发稿不少于150篇，需要提供所有发稿链接\n4.报告反馈：双周报、月报（PPT）、结案报告（PPT）",
    "platform": "5个平台",
    "notes": "",
    "manager": "马朔",
    "writer": "马朔",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcfxZ1",
    "source": "feishu",
    "name": "全标",
    "status": "已完成",
    "startDate": "2025-10-11",
    "cycleDays": 14,
    "progressPercent": 100,
    "kpi": "AI咨询",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcfeUR",
    "source": "feishu",
    "name": "7 THLAT",
    "status": "已完成",
    "startDate": "2026-03-16",
    "cycleDays": 30,
    "progressPercent": 100,
    "kpi": "品牌名 信息正确展现",
    "platform": "豆包，千问",
    "notes": "",
    "manager": "刘依晨",
    "writer": "邢瑜轩",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcxETh",
    "source": "feishu",
    "name": "公交",
    "status": "已完成",
    "startDate": "2026-03-23",
    "cycleDays": 30,
    "progressPercent": 100,
    "kpi": "三个关键词覆盖度>60%",
    "platform": "大于等于3个主流AI大模型",
    "notes": "",
    "manager": "金雨婷",
    "writer": "金雨婷",
    "publisher": "刘依晨",
    "monitor": "金雨婷、刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcWAzC",
    "source": "feishu",
    "name": "祖玛珑",
    "status": "已完成",
    "startDate": "2026-03-29",
    "cycleDays": 51,
    "progressPercent": 100,
    "kpi": "",
    "platform": "豆包app",
    "notes": "",
    "manager": "赵博宇",
    "writer": "邢瑜轩",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcnwiZ",
    "source": "feishu",
    "name": "mac",
    "status": "停滞",
    "startDate": "2026-03-29",
    "cycleDays": 92,
    "progressPercent": 52,
    "kpi": "",
    "platform": "豆包app+deepseek",
    "notes": "",
    "manager": "赵博宇",
    "writer": "马朔",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcetxW",
    "source": "feishu",
    "name": "海蓝之谜",
    "status": "停滞",
    "startDate": "2026-03-29",
    "cycleDays": 92,
    "progressPercent": 54,
    "kpi": "",
    "platform": "豆包app",
    "notes": "",
    "manager": "赵博宇",
    "writer": "赵博宇",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcXYmU",
    "source": "feishu",
    "name": "欧莱雅",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcjm2W",
    "source": "feishu",
    "name": "作业帮",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOc7fXw",
    "source": "feishu",
    "name": "施耐德",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOceANM",
    "source": "feishu",
    "name": "babycare招标",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "3月24日递交应标文件@向昱筱Cheryl Xiang ✅",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOc4DBR",
    "source": "feishu",
    "name": "招行信用卡",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcE3VX",
    "source": "feishu",
    "name": "贵州天马",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOc37li",
    "source": "feishu",
    "name": "谷雨",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcECQL",
    "source": "feishu",
    "name": "嘉立创",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcIuxf",
    "source": "feishu",
    "name": "施耐德",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "本周完成竞标方案@向昱筱Cheryl Xiang",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOc0BKa",
    "source": "feishu",
    "name": "时空宇道",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "本周完成竞标方案@向昱筱Cheryl Xiang",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOcszqo",
    "source": "feishu",
    "name": "中商联数据委",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "@向昱筱Cheryl Xiang @马朔",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recveNplOctD7v",
    "source": "feishu",
    "name": "wonderlab",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "@向昱筱Cheryl Xiang本周五前给方案",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvgopfFqMfp4",
    "source": "feishu",
    "name": "理想",
    "status": "已完成",
    "startDate": "2026-04-09",
    "cycleDays": 5,
    "progressPercent": 100,
    "kpi": "",
    "platform": "产品展示度，提升至不低于90%",
    "notes": "",
    "manager": "辛味珈、飞书用户6916HP",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXpRFrA1MC",
    "source": "feishu",
    "name": "哲库林 润喉糖",
    "status": "进行中",
    "startDate": "2026-05-07",
    "cycleDays": 153,
    "progressPercent": 20,
    "kpi": "关键词：蜂胶润喉糖、教师节润喉糖、教师节润喉护嗓礼物\n5-6月：Zirkulin哲库林无糖蜂胶润喉糖、蜂胶润喉糖、教师节润喉糖、教师节护嗓润喉礼物\n7-10月：Zirkulin哲库林无糖蜂胶润喉糖、蜂胶润喉糖、教师节润喉糖、教师节礼物",
    "platform": "（DeepSeek、豆包、Kimi、通义千\n问、元宝，以下简称“目标平台”）中的80%有效收录。\n要求：主攻教师节场景",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXpWChLgnp",
    "source": "feishu",
    "name": "爱菊学校",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXq5d4Oxv0",
    "source": "feishu",
    "name": "海尔（卡萨帝）",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXqn6kl16F",
    "source": "feishu",
    "name": "雀巢",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇、飞书用户6916HP",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXqxeQlGwN",
    "source": "feishu",
    "name": "珍致",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇、飞书用户6916HP",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXr75uIOhW",
    "source": "feishu",
    "name": "骨科医生",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "刘依晨",
    "writer": "刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvhXr8SD77ql",
    "source": "feishu",
    "name": "乳腺癌医生",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "邢瑜轩",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvjh9izeBYrC",
    "source": "feishu",
    "name": "igus",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvjheWColObr",
    "source": "feishu",
    "name": "一丰 荣放 亚洲龙",
    "status": "进行中",
    "startDate": "2026-05-05",
    "cycleDays": 91,
    "progressPercent": 36,
    "kpi": "亚洲龙KPI的考核：\n提升目标：声量SOV ：≥15%；TOP3推荐度：≥30%；TOP10推荐度：≥80%\n优化稿件：>= 100篇\n\n荣放KPI的考核\n提升目标：声量SOV ：≥15%；TOP3推荐度：≥20%；TOP10推荐度：≥80%",
    "platform": "5个平台",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvjhfX2i6zgu",
    "source": "feishu",
    "name": "智美",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "宋芷桐",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvjW5TB0WiZd",
    "source": "feishu",
    "name": "格力高",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "收录即可 \n备注：以信源清单为目标",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvjW5VFLM2L1",
    "source": "feishu",
    "name": "深演",
    "status": "进行中",
    "startDate": "2026-05-14",
    "cycleDays": 30,
    "progressPercent": 80,
    "kpi": "大模型关键词正向提及率超过90%，需要发稿大于36篇（提供发稿链接）",
    "platform": "",
    "notes": "",
    "manager": "宋芷桐",
    "writer": "宋芷桐",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvjW6XlvkgV3",
    "source": "feishu",
    "name": "半亩花田",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvkB4pIdAQ48",
    "source": "feishu",
    "name": "长安汽车",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvkB4roXUK2R",
    "source": "feishu",
    "name": "咪咕",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvkB4MgLZqyP",
    "source": "feishu",
    "name": "万豪",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvkB4Qxo6Obm",
    "source": "feishu",
    "name": "自然堂",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvkB54wk2Wq0",
    "source": "feishu",
    "name": "pxn",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvld4x7F5xhp",
    "source": "feishu",
    "name": "赏·会所",
    "status": "进行中",
    "startDate": "2026-05-31",
    "cycleDays": 91,
    "progressPercent": 18,
    "kpi": "优化 14 天起出效果，第一个月收录，第二个月进前 5，第三个月到前 3\n发稿要求：第一个月目标是收录，每篇发 2-3 个媒体，暂未要求稿件数据",
    "platform": "六个平台中四个及以上，80%时间",
    "notes": "",
    "manager": "宋芷桐",
    "writer": "宋芷桐",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "待确认"
  },
  {
    "id": "recvln50lusVeg",
    "source": "feishu",
    "name": "北京大学深圳研究生院",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "收录即可\n五个关键词",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认"
  }
];
window.FEISHU_SYNC_META = {
  "fetchedAt": "2026-06-08T09:43:39.979Z",
  "projectCount": 48,
  "reportCount": 48,
  "invoiceCount": 0,
  "tables": [
    "项目进度",
    "周报月报"
  ],
  "statusNote": "Stage 字段暂未由飞书记录接口返回；停滞按截图校正，已提交/无排期映射为待开始。"
};
