window.FEISHU_PROJECTS = [
  {
    "id": "recvm25hMZaywX",
    "source": "feishu",
    "name": "湄洲岛",
    "status": "已完成",
    "startDate": "2025-12-17",
    "cycleDays": 5,
    "progressPercent": 100,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "张扬",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/FPtlwteXAiIJNSkG22qcmU9enPw"
      }
    ],
    "kpiStatus": "已完成待补 KPI",
    "currentData": "已关联 1 个监测表入口；项目周期已结束，待补充 KPI 与结案资料。",
    "optimizationSuggestion": "补充项目 KPI 与优化平台；监测表已关联，后续可归档周报/结案报告。",
    "reportLinks": []
  },
  {
    "id": "rec25v3tGmrDdx",
    "source": "feishu",
    "name": "西昊",
    "status": "停滞",
    "startDate": "2025-11-17",
    "cycleDays": 377,
    "progressPercent": 47,
    "kpi": "人体工学椅、办公椅、电竞椅、电脑椅排名前三",
    "platform": "全平台5及以上",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈、张扬",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/GckTwsRTni879KkUFfQctuMCnoh"
      }
    ],
    "kpiStatus": "停滞待处理",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "监测表已关联；项目停滞中，需结合最新监测补充恢复推进或暂停说明。",
    "reportLinks": [
      {
        "label": "氧气科技 西昊GEO SOLUTION1021final.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "F246bPExNomnc3xOJOxcmTkCnDf",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 45365379
      },
      {
        "label": "第二个月【简洁版】 西昊x氧气 GEO月报.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "FckebtwUuoI9kRxcI4gcm1VinPf",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 24023616
      },
      {
        "label": "第三个月 西昊x氧气 GEO月报 1.22-2.22.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "XVPUbINv8obyk8xDka0cdxU2nJr",
        "fileType": "application/pdf",
        "size": 3593312
      }
    ]
  },
  {
    "id": "recveNaDKVJG3t",
    "source": "feishu",
    "name": "西昊2",
    "status": "停滞",
    "startDate": "2026-01-11",
    "cycleDays": 365,
    "progressPercent": 35,
    "kpi": "撑腰护背久坐不累，实现在该关键词下的品牌排名第一（跨品类总排名第一）考核标准：首月仅考核最后一周，即3个平台完成天数≥4，则视为完成(如上表，第一月第4周完成天数为3，为视为未完成);第二个月开始进入正常考核周期：每个平台、每周周一至周五(含节假日)，即每月20天，任意完成天数≥16，则视为本月100%达标。",
    "platform": "DeepSeek、豆包、文心一言",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "停滞待处理",
    "currentData": "当前完成度 35%",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": []
  },
  {
    "id": "recveNlgg5OPg6",
    "source": "feishu",
    "name": "可口可乐",
    "status": "已完成",
    "startDate": "2025-12-02",
    "cycleDays": 31,
    "progressPercent": 100,
    "kpi": "负面关联降低",
    "platform": "微博智搜",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/QkMywkQRIi1ko3ku0sfcvQr0nGb"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "监测表已关联；项目已完成，建议归档监测结论和结案报告。",
    "reportLinks": []
  },
  {
    "id": "recveNouG3UhTD",
    "source": "feishu",
    "name": "茶马古窖",
    "status": "已完成",
    "startDate": "2025-02-11",
    "cycleDays": 337,
    "progressPercent": 100,
    "kpi": "个人ip",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈、刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/ZYRywZbsVisSyCk7e8YcBUO5nzd"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "监测表已关联；项目已完成，建议补充结案资料并归档监测结果。",
    "reportLinks": []
  },
  {
    "id": "recveNpiTYQzHi",
    "source": "feishu",
    "name": "太太乐松茸鲜",
    "status": "进行中",
    "startDate": "2026-02-09",
    "cycleDays": 365,
    "progressPercent": 32,
    "kpi": "10个关键词排名第一，500篇（-27.4.14）",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "梁伟安",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/MZBYwDkEJirM5kkXbSicUTPQn8f?sheet=BWsvDf"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/OPYxwvF9CiWCV9ksQfHcv0cunZb?sheet=vcWSnP"
      }
    ],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 4 个工作表，有效发布链接 304 条。\n监测表已读取 1 个工作表，最新日期 2026-06-04。\n监测表识别到排名数据 14 条，其中 Top3 5 条、Top10 9 条。\n收录/提及相关记录：正向 17 条，未收录 0 条。\n排名第一 KPI：目标 10 个关键词；当前需用监测表关键词维度继续核对“排名第一”数量。",
    "optimizationSuggestion": "把监测表中的关键词、平台、排名整理为固定列，便于自动判断排名第一达成数。",
    "reportLinks": [
      {
        "label": "太太乐0504-0531监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "QNZubWcUDo5vDHxJgo4cXbQTntd",
        "fileType": "application/pdf",
        "size": 603268
      },
      {
        "label": "太太乐0511-0517监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "H9qSb57f7oR0ILxi8O5cZfDqnDd",
        "fileType": "application/pdf",
        "size": 687611
      },
      {
        "label": "太太乐0518-0524监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "Y36hbTlmXoau8vxSfyNcoVTknlf",
        "fileType": "application/pdf",
        "size": 865416
      },
      {
        "label": "太太乐松茸鲜_GEO_审计报告_(0511-0517).docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "MHj1bx8wjovQbuxCdgicdebRntf",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 23170
      },
      {
        "label": "太太乐0525-0531监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "MkBSbo3HvoCjPsxQyIrc1JxlncS",
        "fileType": "application/pdf",
        "size": 665018
      },
      {
        "label": "太太乐GEO监测报告（0518-0524）.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "T16cbE1C4owpPYx9YzqcidkXnXg",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 164563
      },
      {
        "label": "太太乐GEO监测报告（0525-0531）.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "AqXHbgDCzoCwfyxJg2wcoWkun4f",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 179670
      },
      {
        "label": "太太乐0601-0607监测折线图.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "IDigbnu0Go6VaOxxzXyckigxnug",
        "fileType": "application/pdf",
        "size": 499019
      },
      {
        "label": "太太乐松茸鲜GEO监测报告部分（5月10日）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "SvBJbnte9ogZt8xUBFqcqY70nug",
        "fileType": "application/pdf",
        "size": 1020810
      },
      {
        "label": "太太乐GEO监测报告（0601-0607）.docx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "JSHDb1Tm8oEdxCxY1dncXUM1nDg",
        "fileType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 179983
      }
    ]
  },
  {
    "id": "recveNplOcrpKw",
    "source": "feishu",
    "name": "李锦记",
    "status": "已完成",
    "startDate": "2026-02-11",
    "cycleDays": 28,
    "progressPercent": 100,
    "kpi": "4个关键词排名前三",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "宋芷桐、刘依晨",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/YLZcwYwFxivdUckaovgc4V4ynyh"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/CIjVwvhj2idT9wkKpmNcSL98nmh"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个发稿资料入口；已关联 1 个监测表入口",
    "optimizationSuggestion": "发稿和监测资料已关联；下一步统计有效发布链接数，并结合监测表汇总近一周/近一月趋势。",
    "reportLinks": [
      {
        "label": "李锦记月度监测与洞察报告0317.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "KxyLbR3HpoaEL2xkw4EcFSKtn7b",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 20092411
      },
      {
        "label": "李锦记薄盐生抽GEO第二阶段监测报告（３月12日结案）.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "BVRCbeIN1oEkz2xFvXWcdLC4ngd",
        "fileType": "application/pdf",
        "size": 2202942
      },
      {
        "label": "深演×李锦记月度合作复盘与后续优化建议.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "IHJkbrTQdoTnZvxqLcrc4kL4nsd",
        "fileType": "application/pdf",
        "size": 2900913
      }
    ]
  },
  {
    "id": "recveNplOcTlEG",
    "source": "feishu",
    "name": "一丰",
    "status": "已完成",
    "startDate": "2026-02-05",
    "cycleDays": 59,
    "progressPercent": 100,
    "kpi": "1个关键词被收录",
    "platform": "DeepSeek",
    "notes": "",
    "manager": "飞书用户6916HP",
    "writer": "辛味珈、刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": [
      {
        "label": "2.6-3.6一汽丰田月报.pdf",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "GqGbbpFMWoRpcTxXMPncyJYDnRb",
        "fileType": "application/pdf",
        "size": 1708118
      }
    ]
  },
  {
    "id": "recveNplOciJ1c",
    "source": "feishu",
    "name": "驾校一点通",
    "status": "已完成",
    "startDate": "2026-02-23",
    "cycleDays": 28,
    "progressPercent": 100,
    "kpi": "4个关键词排名前三",
    "platform": "全平台4及以上",
    "notes": "",
    "manager": "赵博宇",
    "writer": "赵博宇",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/sheets/LEqSs3Vsmhn8vEt8BAscioL1nob"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/EgLLwBbWXiQokskbPYacSSOSnxf"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个发稿资料入口；已关联 1 个监测表入口",
    "optimizationSuggestion": "发稿和监测资料已关联；下一步统计有效发布链接数，核对 KPI 缺口。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcdyyk",
    "source": "feishu",
    "name": "华硕",
    "status": "进行中",
    "startDate": "2026-04-12",
    "cycleDays": 91,
    "progressPercent": 88,
    "kpi": "1.在服务周期结束时，该语义包在指定的主流AI大模型矩阵（按照本次项目指定的五大平台：DeepSeek、豆包、kimi、腾讯元宝、通义千问）中的智能搜索结果，实现正面、准确信息的覆盖率为5个的大模型平台华硕主板，华硕商城在推荐位≥3位。\n2.从项目启动开始的20天需要看到优化结果，从项目启动30天需要看到稳定的优化结果，一直到项目合作结束。需提供必要的搜索验证页面截图（至少30个账号）\n3.一个季度发稿不少于150篇，需要提供所有发稿链接\n4.报告反馈：双周报、月报（PPT）、结案报告（PPT）",
    "platform": "5个平台",
    "notes": "",
    "manager": "马朔",
    "writer": "马朔",
    "publisher": "刘依晨",
    "monitor": "宋芷桐",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/KbsdwkRTBizuvgkePKOcvyGAnlb?sheet=QhQovf"
      }
    ],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/VzrDwYafWixoRqkTMdHcBKupngx?sheet=DGmpZZ"
      }
    ],
    "kpiStatus": "未达标",
    "currentData": "发稿表已按子项目核对：华硕主板 100/150 篇，还差 50 篇；华硕商城 78/150 篇，还差 72 篇。\n两个子项目均要求各 150 篇，不能按主板+商城合并总数判断达标。\n监测表已读取 1 个工作表，最新日期 2026-06-02。\n监测表识别到排名数据 50 条，其中 Top3 50 条、Top10 50 条；收录/提及相关记录正向 27 条，未收录 0 条。",
    "optimizationSuggestion": "优先补齐发稿缺口：华硕主板补 50 篇、华硕商城补 72 篇；后续发稿表保持主板/商城分表统计，不再用合并总数判断 KPI。监测表继续按周更新，并补充双周报/月报归档。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcfxZ1",
    "source": "feishu",
    "name": "全标",
    "status": "已完成",
    "startDate": "2025-10-11",
    "cycleDays": 14,
    "progressPercent": 100,
    "kpi": "AI咨询",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcfeUR",
    "source": "feishu",
    "name": "7 THLAT",
    "status": "已完成",
    "startDate": "2026-03-16",
    "cycleDays": 30,
    "progressPercent": 100,
    "kpi": "品牌名 信息正确展现",
    "platform": "豆包，千问",
    "notes": "",
    "manager": "刘依晨",
    "writer": "邢瑜轩",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcxETh",
    "source": "feishu",
    "name": "公交",
    "status": "已完成",
    "startDate": "2026-03-23",
    "cycleDays": 30,
    "progressPercent": 100,
    "kpi": "三个关键词覆盖度>60%",
    "platform": "大于等于3个主流AI大模型",
    "notes": "",
    "manager": "金雨婷",
    "writer": "金雨婷",
    "publisher": "刘依晨",
    "monitor": "金雨婷、刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcWAzC",
    "source": "feishu",
    "name": "祖玛珑",
    "status": "已完成",
    "startDate": "2026-03-29",
    "cycleDays": 51,
    "progressPercent": 100,
    "kpi": "",
    "platform": "豆包app",
    "notes": "",
    "manager": "赵博宇",
    "writer": "邢瑜轩",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "已达标",
    "currentData": "当前完成度 100%",
    "optimizationSuggestion": "保持监测数据归档，补充结案资料与发稿链接。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcnwiZ",
    "source": "feishu",
    "name": "mac",
    "status": "停滞",
    "startDate": "2026-03-29",
    "cycleDays": 92,
    "progressPercent": 52,
    "kpi": "",
    "platform": "豆包app+deepseek",
    "notes": "",
    "manager": "赵博宇",
    "writer": "马朔",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "停滞待处理",
    "currentData": "当前完成度 52%",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcetxW",
    "source": "feishu",
    "name": "海蓝之谜",
    "status": "停滞",
    "startDate": "2026-03-29",
    "cycleDays": 92,
    "progressPercent": 54,
    "kpi": "",
    "platform": "豆包app",
    "notes": "",
    "manager": "赵博宇",
    "writer": "赵博宇",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "停滞待处理",
    "currentData": "当前完成度 54%",
    "optimizationSuggestion": "确认项目是否恢复推进；优先补充停滞原因、发稿链接和最新监测表。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcXYmU",
    "source": "feishu",
    "name": "欧莱雅",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcjm2W",
    "source": "feishu",
    "name": "作业帮",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOc7fXw",
    "source": "feishu",
    "name": "施耐德",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOceANM",
    "source": "feishu",
    "name": "babycare招标",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "3月24日递交应标文件@向昱筱Cheryl Xiang ✅",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOc4DBR",
    "source": "feishu",
    "name": "招行信用卡",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcE3VX",
    "source": "feishu",
    "name": "贵州天马",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOc37li",
    "source": "feishu",
    "name": "谷雨",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcECQL",
    "source": "feishu",
    "name": "嘉立创",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcIuxf",
    "source": "feishu",
    "name": "施耐德",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "本周完成竞标方案@向昱筱Cheryl Xiang",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOc0BKa",
    "source": "feishu",
    "name": "时空宇道",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "本周完成竞标方案@向昱筱Cheryl Xiang",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOcszqo",
    "source": "feishu",
    "name": "中商联数据委",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "@向昱筱Cheryl Xiang @马朔",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recveNplOctD7v",
    "source": "feishu",
    "name": "wonderlab",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "@向昱筱Cheryl Xiang本周五前给方案",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvgopfFqMfp4",
    "source": "feishu",
    "name": "理想",
    "status": "已完成",
    "startDate": "2026-04-09",
    "cycleDays": 5,
    "progressPercent": 100,
    "kpi": "",
    "platform": "产品展示度，提升至不低于90%",
    "notes": "",
    "manager": "辛味珈、飞书用户6916HP",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/LEc9wkYGHiuVT5kLmVUcN2I7nzg"
      }
    ],
    "kpiStatus": "已达标",
    "currentData": "已关联 1 个监测表入口",
    "optimizationSuggestion": "监测表已关联；下一步补充发稿资料，并按近一周/近一月整理趋势。",
    "reportLinks": []
  },
  {
    "id": "recvhXpRFrA1MC",
    "source": "feishu",
    "name": "哲库林 润喉糖",
    "status": "进行中",
    "startDate": "2026-05-07",
    "cycleDays": 153,
    "progressPercent": 20,
    "kpi": "关键词：蜂胶润喉糖、教师节润喉糖、教师节润喉护嗓礼物\n5-6月：Zirkulin哲库林无糖蜂胶润喉糖、蜂胶润喉糖、教师节润喉糖、教师节护嗓润喉礼物\n7-10月：Zirkulin哲库林无糖蜂胶润喉糖、蜂胶润喉糖、教师节润喉糖、教师节礼物",
    "platform": "（DeepSeek、豆包、Kimi、通义千\n问、元宝，以下简称“目标平台”）中的80%有效收录。\n要求：主攻教师节场景",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/V0MZwOwgWicvockfGZicr0r1nvb"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 1 个工作表，有效发布链接 49 条。\n尚未关联监测表，暂无法判断近一周/近一月趋势。",
    "optimizationSuggestion": "补充监测表入口，否则只能核算发稿，无法判断排名、收录和趋势。",
    "reportLinks": []
  },
  {
    "id": "recvhXpWChLgnp",
    "source": "feishu",
    "name": "爱菊学校",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvhXq5d4Oxv0",
    "source": "feishu",
    "name": "海尔（卡萨帝）",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvhXqn6kl16F",
    "source": "feishu",
    "name": "雀巢",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇、飞书用户6916HP",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvhXqxeQlGwN",
    "source": "feishu",
    "name": "珍致",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇、飞书用户6916HP",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvhXr75uIOhW",
    "source": "feishu",
    "name": "骨科医生",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "刘依晨",
    "writer": "刘依晨",
    "publisher": "刘依晨",
    "monitor": "刘依晨",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": [
      {
        "label": "吴敏飞教授AI语料优化结案报告(2).pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "CvWibY5cooaDPxxtnTVcLNybnRd",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 13684131
      }
    ]
  },
  {
    "id": "recvhXr8SD77ql",
    "source": "feishu",
    "name": "乳腺癌医生",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "邢瑜轩",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvjh9izeBYrC",
    "source": "feishu",
    "name": "igus",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "赵博宇",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvjheWColObr",
    "source": "feishu",
    "name": "一丰 荣放 亚洲龙",
    "status": "进行中",
    "startDate": "2026-05-05",
    "cycleDays": 91,
    "progressPercent": 36,
    "kpi": "亚洲龙KPI的考核：\n提升目标：声量SOV ：≥15%；TOP3推荐度：≥30%；TOP10推荐度：≥80%\n优化稿件：>= 100篇\n\n荣放KPI的考核\n提升目标：声量SOV ：≥15%；TOP3推荐度：≥20%；TOP10推荐度：≥80%",
    "platform": "5个平台",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/XDQhwi6bTiZVrlkmQQEch7Bgn0c",
        "label": "一丰荣放亚洲龙 发稿附表"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "部分未达标",
    "currentData": "正式发稿附表已读取：有效发布链接 90 条，其中荣放 36 条、亚洲龙 54 条。\n发稿 KPI：90/100 篇，还差 10 篇；以新飞书附表为准，之前本地周报统计口径已废弃。\n亚洲龙 6/7 KPI 表：6 个基础词的 SOV、Top3、Top10 综合值均达标；最新综合 SOV 20.6%-27.7%、Top3 57.0%-68.9%、Top10 82.7%-89.3%。\n荣放 5/20 点检表：Top3 38.51% 已超过 ≥20%；SOV 7.63% 距 ≥15% 还差 7.37 个百分点；Top10 47.24% 距 ≥80% 还差 32.76 个百分点。",
    "optimizationSuggestion": "先补齐正式发稿附表中的 10 篇发布缺口；荣放侧继续重点补 SOV 与 Top10，增加汽车垂媒/问答信源覆盖，围绕“15万左右通勤SUV、城市SUV、家用SUV”等词做定向发布和监测复盘。",
    "reportLinks": [
      {
        "label": "亚洲龙-5月14号-GEO截图.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "JDOnb6zPlo2tihxcfNncVjzwn5z",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 55134846
      },
      {
        "label": "荣放-5月14号-GEO截图.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "AiXWbDC8jopFdAxkj67cPYYwnUd",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 28867749
      },
      {
        "label": "【亚洲龙】基础词数据&信源-截至6.7.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "W9OCbyuLAoYvR0xEzDBcT5ksnGb",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 1188592
      },
      {
        "label": "一汽丰田-荣放GEO诊断项目-周报0501至0514（深演）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "H926bMbqxoe1bHxNgD7cy0HFnFg",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 583034
      },
      {
        "label": "周报点检-车型GEO优化进展（深演）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "OH1XbAf1KoGBS4xXFHlcqMRInCd",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 16103
      },
      {
        "label": "一汽丰田-亚洲龙GEO诊断项目-周报0511至0517（深演）.xlsx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "WQ1MbrKQWo9niuxwY1AcxNhfn2c",
        "fileType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "size": 586388
      },
      {
        "label": "一丰geo 5月阶段分析.pptx",
        "url": "https://jcnquengglen.feishu.cn/base/SRjgbQqBMa6L1isu8CFcuUAAnEb?table=tbl8o6BzxfDpqxMX&view=vew234Y6ro",
        "fileToken": "NcdzbkqYTogt0xxS9yocvzHcnwh",
        "fileType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "size": 151938
      }
    ]
  },
  {
    "id": "recvjhfX2i6zgu",
    "source": "feishu",
    "name": "智美",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "宋芷桐",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvjW5TB0WiZd",
    "source": "feishu",
    "name": "格力高",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "收录即可 \n备注：以信源清单为目标",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "辛味珈",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvjW5VFLM2L1",
    "source": "feishu",
    "name": "深演",
    "status": "进行中",
    "startDate": "2026-05-14",
    "cycleDays": 30,
    "progressPercent": 80,
    "kpi": "大模型关键词正向提及率超过90%，需要发稿大于36篇（提供发稿链接）",
    "platform": "",
    "notes": "",
    "manager": "宋芷桐",
    "writer": "宋芷桐",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/Fe3uwVLCViswdxkzRKUcaQzqnug"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 1 个工作表，有效发布链接 53 条。\n发稿 KPI：53/36 篇，已达到数量要求。\n尚未关联监测表，暂无法判断近一周/近一月趋势。",
    "optimizationSuggestion": "补充监测表入口，否则只能核算发稿，无法判断排名、收录和趋势。",
    "reportLinks": []
  },
  {
    "id": "recvjW6XlvkgV3",
    "source": "feishu",
    "name": "半亩花田",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvkB4pIdAQ48",
    "source": "feishu",
    "name": "长安汽车",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvkB4roXUK2R",
    "source": "feishu",
    "name": "咪咕",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvkB4MgLZqyP",
    "source": "feishu",
    "name": "万豪",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvkB4Qxo6Obm",
    "source": "feishu",
    "name": "自然堂",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvkB54wk2Wq0",
    "source": "feishu",
    "name": "pxn",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "",
    "platform": "",
    "notes": "",
    "manager": "",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "待确认",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  },
  {
    "id": "recvld4x7F5xhp",
    "source": "feishu",
    "name": "赏·会所",
    "status": "进行中",
    "startDate": "2026-05-31",
    "cycleDays": 91,
    "progressPercent": 18,
    "kpi": "优化 14 天起出效果，第一个月收录，第二个月进前 5，第三个月到前 3\n发稿要求：第一个月目标是收录，每篇发 2-3 个媒体，暂未要求稿件数据",
    "platform": "六个平台中四个及以上，80%时间",
    "notes": "",
    "manager": "宋芷桐",
    "writer": "宋芷桐",
    "publisher": "刘依晨",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [
      {
        "url": "https://jcnquengglen.feishu.cn/wiki/RmRwwx6XKiyvxZkI1zBcE5OZnzf"
      }
    ],
    "monitorLinks": [],
    "kpiStatus": "推进中",
    "currentData": "发稿表已读取 1 个工作表，有效发布链接 7 条。\n尚未关联监测表，暂无法判断近一周/近一月趋势。",
    "optimizationSuggestion": "补充监测表入口，否则只能核算发稿，无法判断排名、收录和趋势。",
    "reportLinks": []
  },
  {
    "id": "recvln50lusVeg",
    "source": "feishu",
    "name": "北京大学深圳研究生院",
    "status": "待开始",
    "startDate": "2026-06-07",
    "cycleDays": 30,
    "progressPercent": 0,
    "kpi": "收录即可\n五个关键词",
    "platform": "",
    "notes": "",
    "manager": "辛味珈",
    "writer": "",
    "publisher": "",
    "monitor": "",
    "invoiceStatus": "已开票",
    "publishLinks": [],
    "monitorLinks": [],
    "kpiStatus": "待开始",
    "currentData": "当前完成度 0%",
    "optimizationSuggestion": "项目启动前补齐排期、发稿计划、监测表链接与负责人。",
    "reportLinks": []
  }
];
window.FEISHU_SYNC_META = {
  "fetchedAt": "2026-06-09T08:34:42.908Z",
  "projectCount": 48,
  "reportCount": 49,
  "invoiceCount": 0,
  "tables": [
    "项目进度",
    "周报月报"
  ],
  "statusNote": "Stage 字段暂未由飞书记录接口返回；停滞按截图校正，已提交/无排期映射为待开始。",
  "updatedAt": "2026-06-09T06:22:53.655Z",
  "syncFields": [
    "网页开票信息",
    "发稿链接",
    "监测表",
    "优化建议",
    "报告链接"
  ],
  "fileSync": {
    "count": 6,
    "projects": [
      {
        "name": "西昊",
        "count": 3
      },
      {
        "name": "太太乐松茸鲜",
        "count": 10
      },
      {
        "name": "李锦记",
        "count": 3
      },
      {
        "name": "一丰",
        "count": 1
      },
      {
        "name": "骨科医生",
        "count": 1
      },
      {
        "name": "一丰 荣放 亚洲龙",
        "count": 7
      }
    ]
  },
  "syncedAt": "2026-06-09T09:43:49.846Z",
  "note": "toyota-official-publish-v18"
};
